import { createLongitudinalCourse, getLongitudinalCoursePositionAtDistance, getLongitudinalCourseProgressAtDistance, getLongitudinalCourseRoadGradeAtDistance, getLongitudinalCourseSegmentIndexAtDistance } from "@rouelibre/sim-core";
import { describe, expect, it } from "vitest";
const segments = [{ startDistanceMeters: 0, roadGrade: 0 }, { startDistanceMeters: 200, roadGrade: 0.05 }, { startDistanceMeters: 400, roadGrade: -0.05 }, { startDistanceMeters: 600, roadGrade: 0 }];
describe("longitudinal course", () => {
  it("creates immutable defensive copies", () => { const input = segments.map((segment) => ({ ...segment })); const course = createLongitudinalCourse(input); const changed = input[1]; if (changed === undefined) throw new Error("missing test segment"); changed.roadGrade = 8; input.push({ startDistanceMeters: 800, roadGrade: 1 }); expect(course.segments).toHaveLength(4); expect(course.segments[1]?.roadGrade).toBe(0.05); expect(Object.isFrozen(course)).toBe(true); expect(Object.isFrozen(course.segments)).toBe(true); expect(Object.isFrozen(course.segments[0])).toBe(true); expect(() => { (course.segments[0] as { roadGrade: number }).roadGrade = 1; }).toThrow(TypeError); });
  it("rejects invalid courses", () => { const invalid = [[], [{ startDistanceMeters: 1, roadGrade: 0 }], [{ startDistanceMeters: -1, roadGrade: 0 }], [{ startDistanceMeters: Number.NaN, roadGrade: 0 }], [{ startDistanceMeters: Number.POSITIVE_INFINITY, roadGrade: 0 }], [{ startDistanceMeters: Number.NEGATIVE_INFINITY, roadGrade: 0 }], [{ startDistanceMeters: 0, roadGrade: Number.NaN }], [{ startDistanceMeters: 0, roadGrade: Number.POSITIVE_INFINITY }], [{ startDistanceMeters: 0, roadGrade: Number.NEGATIVE_INFINITY }], [{ startDistanceMeters: 0, roadGrade: 0 }, { startDistanceMeters: 0, roadGrade: 0 }], [{ startDistanceMeters: 0, roadGrade: 0 }, { startDistanceMeters: 2, roadGrade: 0 }, { startDistanceMeters: 1, roadGrade: 0 }]]; for (const input of invalid) expect(() => createLongitudinalCourse(input)).toThrow(RangeError); });
  it("resolves semi-open boundaries and extends the final segment", () => { const course = createLongitudinalCourse(segments); for (const [distance, expected] of [[0, 0], [199.999, 0], [200, 1], [399.999, 1], [400, 2], [600, 3], [10_000, 3]] as const) expect(getLongitudinalCourseSegmentIndexAtDistance(course, distance)).toBe(expected); expect(getLongitudinalCourseRoadGradeAtDistance(course, 400)).toBe(-0.05); expect(getLongitudinalCoursePositionAtDistance(course, 250)).toMatchObject({ segmentIndex: 1, segmentCount: 4, segmentStartDistanceMeters: 200, distanceIntoSegmentMeters: 50, nextSegmentStartDistanceMeters: 400, roadGrade: 0.05 }); expect(getLongitudinalCoursePositionAtDistance(course, 600).nextSegmentStartDistanceMeters).toBeUndefined(); });
  it("rejects invalid resolution distances and is deterministic", () => { const course = createLongitudinalCourse(segments); for (const distance of [Number.NaN, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, -1]) expect(() => getLongitudinalCourseSegmentIndexAtDistance(course, distance)).toThrow(RangeError); expect(getLongitudinalCourseRoadGradeAtDistance(course, 400)).toBe(getLongitudinalCourseRoadGradeAtDistance(course, 400)); });
  it("creates a finite course with immutable explicit total length", () => { const options = { totalLengthMeters: 800 }; const course = createLongitudinalCourse(segments, options); options.totalLengthMeters = 900; expect(course.totalLengthMeters).toBe(800); expect(Object.isFrozen(course)).toBe(true); });
  it("rejects invalid finite total lengths", () => { for (const totalLengthMeters of [0, -1, Number.NaN, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, 600, 599.999]) expect(() => createLongitudinalCourse(segments, { totalLengthMeters })).toThrow(RangeError); expect(createLongitudinalCourse(segments).totalLengthMeters).toBeUndefined(); });
  it("reports bounded finite progress and no invented finish for an endless course", () => { const finite = createLongitudinalCourse(segments, { totalLengthMeters: 800 }); expect(getLongitudinalCourseProgressAtDistance(finite, 200)).toMatchObject({ totalLengthMeters: 800, distanceMeters: 200, remainingDistanceMeters: 600, progress: 0.25, isFinished: false }); expect(getLongitudinalCourseProgressAtDistance(finite, 800)).toMatchObject({ remainingDistanceMeters: 0, progress: 1, isFinished: true }); expect(getLongitudinalCourseProgressAtDistance(finite, 900)).toMatchObject({ remainingDistanceMeters: 0, progress: 1, isFinished: true }); expect(getLongitudinalCourseProgressAtDistance(createLongitudinalCourse(segments), 900)).toMatchObject({ remainingDistanceMeters: undefined, progress: undefined, isFinished: undefined }); });
});
