import { computeSingleRiderForcesAtPower, defaultSingleRiderProfile } from "@rouelibre/sim-core";
import { describe, expect, it } from "vitest";
import { createLabSimulation, LAB_DEMONSTRATION_COURSE, LAB_ENERGY_PROFILE } from "./labSimulation.js";
const closeTo = (a: number, b: number, d = 8) => expect(a).toBeCloseTo(b, d);
const run = (power: number, wind: number, ticks: number, gradePercent = 0) => { const s = createLabSimulation(); s.setRequestedPowerWatts(power); s.setWindSpeedMetersPerSecond(wind); s.setRoadGradePercent(gradePercent); s.stepTicks(ticks); return s.getSnapshot(); };
describe("lab simulation controller", () => {
  it("preserves the initial constant course and controls", () => { const snap = createLabSimulation().getSnapshot(); expect(snap.courseMode).toBe("constant"); expect(snap.course.segments).toEqual([{ startDistanceMeters: 0, roadGrade: 0 }]); expect(snap.environment.roadGrade).toBe(0); expect(snap.energyState.anaerobicReserveJoules).toBe(20_000); });
  it("preserves constant grade conversion and historical simulation", () => { expect(run(250, 0, 60, 5).environment.roadGrade).toBe(0.05); expect(run(250, 3, 1800).physicalState.speedMetersPerSecond).toBeLessThan(run(250, 0, 1800).physicalState.speedMetersPerSecond); });
  it("uses the demonstration course at exact boundaries", () => { const s = createLabSimulation(); s.setCourseMode("demonstration"); expect(s.getSnapshot().course).toBe(LAB_DEMONSTRATION_COURSE); expect(s.getSnapshot().coursePosition.segmentIndex).toBe(0); s.setRequestedPowerWatts(0); s.stepTicks(0); expect(s.getSnapshot().environment.roadGrade).toBe(0); });
  it("exposes the fixed demonstration definitions", () => { expect(LAB_DEMONSTRATION_COURSE.segments.map((segment) => [segment.startDistanceMeters, segment.roadGrade])).toEqual([[0, 0], [200, 0.05], [400, -0.05], [600, 0]]); });
  it("uses the new segment at the tick following a boundary crossing", () => { const s = createLabSimulation(); s.setCourseMode("demonstration"); s.setRequestedPowerWatts(1200); while (s.getSnapshot().physicalState.distanceMeters < 200) s.stepTicks(1); expect(s.getSnapshot().environment.roadGrade).toBe(0.05); s.stepTicks(1); expect(s.getSnapshot().environment.roadGrade).toBe(0.05); });
  it("keeps mode and constant setting after reset", () => { const s = createLabSimulation(); s.setRoadGradePercent(-5); s.setCourseMode("demonstration"); s.stepTicks(600); s.reset(); expect(s.getSnapshot().courseMode).toBe("demonstration"); expect(s.getSnapshot().coursePosition.segmentIndex).toBe(0); s.setCourseMode("constant"); expect(s.getSnapshot().environment.roadGrade).toBe(-0.05); });
  it("is deterministic and exposes frozen course observations", () => { const a = createLabSimulation(); const b = createLabSimulation(); a.setCourseMode("demonstration"); b.setCourseMode("demonstration"); a.stepTicks(7200); b.stepTicks(7200); expect(a.getSnapshot()).toEqual(b.getSnapshot()); expect(Object.isFrozen(a.getSnapshot().course)).toBe(true); expect(Object.isFrozen(a.getSnapshot().coursePosition)).toBe(true); });
  it("matches the documented 120 second segmented benchmark", () => { const s = createLabSimulation(); s.setCourseMode("demonstration"); s.stepTicks(7_200); const snap = s.getSnapshot(); expect(snap.physicalState.distanceMeters).toBeCloseTo(1060.5089829626077, 6); expect(snap.physicalState.speedMetersPerSecond).toBeCloseTo(10.38827553709402, 6); expect(snap.coursePosition.segmentIndex).toBe(3); expect(snap.environment.roadGrade).toBe(0); expect(snap.energyState.anaerobicReserveJoules).toBe(20_000); });
  it("computes forces from produced power and resets energy", () => { const s = createLabSimulation(); s.setRequestedPowerWatts(350); s.stepTicks(12_001); const snap = s.getSnapshot(); closeTo(snap.forces.propulsiveForceNewtons, computeSingleRiderForcesAtPower(snap.physicalState, defaultSingleRiderProfile, snap.environment, snap.physicalState.producedPowerWatts).propulsiveForceNewtons); s.reset(); expect(s.getSnapshot().energyState.anaerobicReserveJoules).toBe(LAB_ENERGY_PROFILE.anaerobicCapacityJoules); });
  it("rejects invalid controls and tick counts", () => { const s = createLabSimulation(); expect(() => s.stepTicks(-1)).toThrow(RangeError); expect(() => s.setCourseMode("other" as "constant")).toThrow(RangeError); });
});
